import type { Metadata } from "next";
import { ChartFigure } from "@/components/ChartFigure";
import { H1, H2, P, Lead, Callout } from "@/components/prose";
import { CHART_GROUPS } from "@/lib/charts";

export const metadata: Metadata = { title: "Chart gallery" };

export default function GalleryPage() {
  const mc = CHART_GROUPS[0];
  const rest = CHART_GROUPS.slice(1);
  const featured = mc.charts[0];

  return (
    <>
      <H1>Chart gallery</H1>
      <Lead>
        Every chart <code className="font-mono text-[0.85em]">edgekit.viz</code> produces, rendered in both themes.
        Toggle light/dark (top-right) and the charts follow. Each is one function call on a backtest&apos;s trades or
        equity — and they compose into the one-call <code className="font-mono text-[0.85em]">tear_sheet</code>.
      </Lead>

      <H2>Monte-Carlo, front and center</H2>
      <P>
        The fan is the honest forward picture: bootstrap the daily returns thousands of times and plot the percentile
        cone. edgekit annotates the terminal 5th / median / 95th outcomes, overlays the realised path, and can append a
        marginal distribution of where a year of paths lands.
      </P>
      <ChartFigure name={featured.id} alt={featured.title} caption={featured.blurb} code={featured.code} />
      <div className="grid gap-4 sm:grid-cols-2">
        {mc.charts.slice(1).map((c) => (
          <ChartFigure key={c.id} name={c.id} alt={c.title} caption={`${c.title} — ${c.blurb}`} />
        ))}
      </div>

      <Callout kind="tip" title="Reproduce these">
        All of these are generated by <code className="font-mono text-[0.85em]">examples/gen_gallery.py</code> from a
        seeded synthetic backtest — no real strategy involved. Run it to regenerate the whole gallery.
      </Callout>

      {rest.map((group) => (
        <section key={group.title}>
          <H2>{group.title}</H2>
          {group.note && <P>{group.note}</P>}
          <div className="grid gap-4 sm:grid-cols-2">
            {group.charts.map((c) => (
              <ChartFigure key={c.id} name={c.id} alt={c.title} caption={`${c.title} — ${c.blurb}`} />
            ))}
          </div>
        </section>
      ))}
    </>
  );
}
